# Generated by Django 3.0.6 on 2021-05-26 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_auto_20200713_2255'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='countLikes',
            field=models.IntegerField(default=0),
        ),
    ]
