# Generated by Django 3.0.6 on 2021-05-26 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_post_countlikes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='countLikes',
        ),
    ]
